spring:
  application:
    name: learn-mybatis
  banner:
    charset: utf-8
  http:
   encoding:
     charset: UTF-8
     enabled: true
     force: true
  messages:
    encoding: UTF-8
  datasource:
       url: jdbc:mysql://127.0.0.1:3306/lin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
       username: root
       password: 123
       driver-class-name: com.mysql.cj.jdbc.Driver
#       type: com.zaxxer.hikari.HikariDataSource
#       hikari:
#         minimum-idle: 5
#         maximum-pool-size: 15
#         auto-commit: true
#         idle-timeout: 30000
#         pool-name: DatebookHikariCP
#         max-lifetime: 1800000
#         connection-timeout: 30000
#         connection-test-query: SELECT 1
# 打印SQL日志 ,键值对的形式 来配置
#logging:
#  level:
#    org.learn.boot.cache.mapper: debug
server:
  port: 8186


